import fs from "node:fs";
import path from "node:path";

// Static export (output: "export") with next-intl localePrefix "as-needed"
// emits the default locale under out/en/, yet every canonical / hreflang /
// sitemap URL declares the English pages at the web root. This script makes
// the build output match what the metadata promises, then generates the
// service worker with a precache list derived from the real build output:
//   1. Promote out/en/* to out/ (so "/" serves English) and drop out/en.
//   2. Patch <html lang> in out/zh/**/*.html from "en" to "zh-CN".
//   3. Emit out/sw.js precaching every generated HTML route + PWA assets.

const out = path.join(process.cwd(), "out");
const en = path.join(out, "en");
const zh = path.join(out, "zh");

if (fs.existsSync(en)) {
  fs.cpSync(en, out, { recursive: true, force: false, errorOnExist: false });
  fs.rmSync(en, { recursive: true });
  console.log("[postbuild] promoted out/en/* -> out/ and removed out/en");
} else {
  console.log("[postbuild] out/en not found - nothing to promote");
}

function patchLang(dir) {
  let patched = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      patched += patchLang(p);
    } else if (entry.name.endsWith(".html")) {
      const html = fs.readFileSync(p, "utf8");
      const next = html.replace('<html lang="en"', '<html lang="zh-CN"');
      if (next !== html) {
        fs.writeFileSync(p, next);
        patched += 1;
      }
    }
  }
  return patched;
}

if (fs.existsSync(zh)) {
  const n = patchLang(zh);
  console.log(`[postbuild] patched <html lang> to zh-CN in ${n} file(s) under out/zh`);
}

// ---- Service worker generation ----
// Collect every route that has an index.html (the promoted root included).
function collectRoutes(dir, prefix = "") {
  const routes = [];
  if (fs.existsSync(path.join(dir, "index.html"))) routes.push(prefix + "/");
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith("_") || entry.name === "404") continue;
    routes.push(...collectRoutes(path.join(dir, entry.name), `${prefix}/${entry.name}`));
  }
  return routes;
}

const routes = collectRoutes(out);
const extras = ["/manifest.webmanifest", "/icon-192.png", "/icon-512.png"].filter((p) =>
  fs.existsSync(path.join(out, p)) || p === "/manifest.webmanifest" || p.startsWith("/icon-")
);
const precache = [...routes, ...extras];
const version = `v${Date.now()}`;

const sw = `// Generated by scripts/postbuild.mjs — do not edit by hand.
const CACHE = "site-${version}";
const PRECACHE = ${JSON.stringify(precache, null, 0)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then(async (cache) => {
      await Promise.allSettled(
        PRECACHE.map((url) =>
          fetch(url, { cache: "reload" })
            .then((res) => (res.ok ? cache.put(url, res) : null))
            .catch(() => {})
        )
      );
    })
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;

  // Immutable build assets: cache-first
  if (url.pathname.startsWith("/_next/static/")) {
    event.respondWith(
      caches.open(CACHE).then((cache) =>
        cache.match(request).then(
          (hit) =>
            hit ||
            fetch(request).then((res) => {
              if (res.ok) cache.put(request, res.clone());
              return res;
            })
        )
      )
    );
    return;
  }

  // Navigations: network-first, cache fallback, then home
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((res) => {
          const clone = res.clone();
          caches.open(CACHE).then((cache) => cache.put(request, clone));
          return res;
        })
        .catch(() =>
          caches.match(request).then((hit) => hit || caches.match("/"))
        )
    );
    return;
  }

  // Everything else (icons, fonts, manifest): stale-while-revalidate
  event.respondWith(
    caches.open(CACHE).then((cache) =>
      cache.match(request).then((hit) => {
        const fetching = fetch(request)
          .then((res) => {
            if (res.ok) cache.put(request, res.clone());
            return res;
          })
          .catch(() => hit);
        return hit || fetching;
      })
    )
  );
});
`;
fs.writeFileSync(path.join(out, "sw.js"), sw);
console.log(`[postbuild] generated out/sw.js — ${precache.length} precached URLs, cache ${version}`);
